//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotonTSapi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class timeunit
    {
        public Nullable<System.DateTime> dateworked { get; set; }
        public string hoursworked { get; set; }
        public string project { get; set; }
        public string timesheet_id { get; set; }
        public string project_id { get; set; }
        [Key]
        public string C_id { get; set; }
    }
}
